services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      - OLLAMA_URL=http://ollama:11434
    restart: unless-stopped
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama_models:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "--version"]
      interval: 30s
      timeout: 10s
      retries: 5

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./src:/srv:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

volumes:
  ollama_models:
  caddy_data:
  caddy_config:
