version: '3.8'
services:
  frontend:
    build: ./  # Assumes your Dockerfile is in the project root
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - appnet

  backend:
    image: python:3.11-alpine
    volumes:
      - ./backend:/app
    working_dir: /app
    command: python app.py
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - appnet

  ollama:
    image: ollama/ollama:latest
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
