services:
  resumereviewer-web:
    build: .
    container_name: resumereviewer-web
    restart: unless-stopped
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
    labels:
      # Enable Traefik for this container
      - "traefik.enable=true"
      
      # Define the router for HTTPS traffic
      - "traefik.http.routers.resumereviewer.rule=Host(`resumereviewer.lukasanell.org`)"
      - "traefik.http.routers.resumereviewer.entrypoints=websecure"
      - "traefik.http.routers.resumereviewer.tls.certresolver=letsencrypt" # Assumes your Traefik cert resolver is named 'letsencrypt'
      
      # Define the service and tell Traefik which port the container is using
      - "traefik.http.services.resumereviewer.loadbalancer.server.port=80"
      
      # Explicitly tell Traefik to use the 'proxy' network for this service
      - "traefik.docker.network=proxy"
      
    networks:
      - proxy

networks:
  proxy:
    external: true
