services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: helloworld_web:latest
    restart: unless-stopped
    networks:
      - webnet

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - webnet

volumes:
  caddy_data:
  caddy_config:

networks:
  webnet: