services:
  backend:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: >
      gunicorn
      --bind 0.0.0.0:8000
      --workers 2
      --worker-class gthread
      --threads 8
      --timeout 120
      --graceful-timeout 30
      --capture-output
      --log-level info
      --config /app/gunicorn_conf.py
      src.app:app
    environment:
      - OLLAMA_URL=http://ollama:11434
      - MODEL_NAME=llama3:8b-instruct-q4_K_M
      - REQUEST_CONNECT_TIMEOUT=5
      - REQUEST_READ_TIMEOUT=90
      - MAX_RESUME_CHARS=6000
      - CACHE_SIZE=64
    restart: unless-stopped
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    volumes:
      - ollama_models:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "--version"]
      interval: 30s
      timeout: 10s
      retries: 5

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./src:/srv:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - backend

volumes:
  ollama_models:
  caddy_data:
  caddy_config:
